/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as TecnicosRouteImport } from './routes/tecnicos'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as ChecklistsIndexRouteImport } from './routes/checklists.index'
import { Route as ChecklistsPlateTypeRouteImport } from './routes/checklists.$plate.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIndexRoute = ChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsPlateTypeRoute = ChecklistsPlateTypeRouteImport.update({
  id: '/checklists/$plate/$type',
  path: '/checklists/$plate/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/tecnicos': typeof TecnicosRoute
  '/veiculos': typeof VeiculosRoute
  '/checklists/': typeof ChecklistsIndexRoute
  '/checklists/$plate/$type': typeof ChecklistsPlateTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/tecnicos': typeof TecnicosRoute
  '/veiculos': typeof VeiculosRoute
  '/checklists': typeof ChecklistsIndexRoute
  '/checklists/$plate/$type': typeof ChecklistsPlateTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/tecnicos': typeof TecnicosRoute
  '/veiculos': typeof VeiculosRoute
  '/checklists/': typeof ChecklistsIndexRoute
  '/checklists/$plate/$type': typeof ChecklistsPlateTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historico'
    | '/tecnicos'
    | '/veiculos'
    | '/checklists/'
    | '/checklists/$plate/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historico'
    | '/tecnicos'
    | '/veiculos'
    | '/checklists'
    | '/checklists/$plate/$type'
  id:
    | '__root__'
    | '/'
    | '/historico'
    | '/tecnicos'
    | '/veiculos'
    | '/checklists/'
    | '/checklists/$plate/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  TecnicosRoute: typeof TecnicosRoute
  VeiculosRoute: typeof VeiculosRoute
  ChecklistsIndexRoute: typeof ChecklistsIndexRoute
  ChecklistsPlateTypeRoute: typeof ChecklistsPlateTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/': {
      id: '/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof ChecklistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/$plate/$type': {
      id: '/checklists/$plate/$type'
      path: '/checklists/$plate/$type'
      fullPath: '/checklists/$plate/$type'
      preLoaderRoute: typeof ChecklistsPlateTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  TecnicosRoute: TecnicosRoute,
  VeiculosRoute: VeiculosRoute,
  ChecklistsIndexRoute: ChecklistsIndexRoute,
  ChecklistsPlateTypeRoute: ChecklistsPlateTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
